import Footer from "@/components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { ReduxProvider } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="bg-gray-50 dark:bg-gray-900 flex flex-col min-h-screen dark:text-white ">
            <Header />
            <div className="flex-grow grid">{children}</div>
            <div className="justify-end">
              <Footer />
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
